version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: manga-store-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "6432:5432"